# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-space
bind-key C-space send-prefix

# split panes using | and -
bind | split-window -h
bind \ split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# switch panes using Alt(option)-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# don't rename windows automatically
set-option -g allow-rename off

# pass keybinds to vim

bind-key -n C-c send-keys C-c
bind-key -n C-x send-keys C-x
set -g default-command "reattach-to-user-namespace -l /bin/zsh"

# enable scrolling

set -g mouse on

# key bind r to reload and shift-m to vim into config

bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"
bind-key M split-window -h "vim ~/.tmux.conf"
